from __future__ import annotations

from enum import IntFlag


class Privileges(IntFlag):
    """Privileges v2 (see docs/reference/privileges.md)."""

    ACTIVATED = 1
    DONOR = 2
    MOD_MANAGE_USERS = 4
    MOD_VIEW_RAP_LOGS = 8
    MOD_MANAGE_REPORTS = 16
    MOD_MANAGE_CLANS = 32
    ADMIN_SEND_ALERTS = 64
    ADMIN_MANAGE_SETTINGS = 128
    ADMIN_MANAGE_BADGES = 256
    ADMIN_MANAGE_PRIVILEGES = 512
    DEV_VIEW_ERROR_LOGS = 1024
    TOURNAMENT_STAFF = 2048
    BOT = 4096
    BN_STD = 8192
    BN_TAIKO = 16384
    BN_CTB = 32768
    BN_MANIA = 65536

    # --- legacy aliases (old panel names -> v2 bits), keep functions.py compiling ---
    USER_NORMAL = ACTIVATED
    USER_DONOR = DONOR
    ADMIN_ACCESS_RAP = MOD_VIEW_RAP_LOGS
    ADMIN_MANAGE_USERS = MOD_MANAGE_USERS
    ADMIN_BAN_USERS = MOD_MANAGE_USERS
    ADMIN_SILENCE_USERS = MOD_MANAGE_USERS
    ADMIN_WIPE_USERS = MOD_MANAGE_USERS
    ADMIN_KICK_USERS = MOD_MANAGE_USERS
    ADMIN_CHAT_MOD = MOD_MANAGE_USERS
    ADMIN_MANAGE_REPORTS = MOD_MANAGE_REPORTS
    ADMIN_MANAGE_SERVERS = ADMIN_MANAGE_SETTINGS
    ADMIN_VIEW_RAP_LOGS = MOD_VIEW_RAP_LOGS
    ADMIN_MANAGE_STD_BEATMAPS = BN_STD
    ADMIN_MANAGE_TAIKO_BEATMAPS = BN_TAIKO
    ADMIN_MANAGE_CATCH_BEATMAPS = BN_CTB
    ADMIN_MANAGE_MANIA_BEATMAPS = BN_MANIA
    ADMIN_MANAGE_BEATMAPS = BN_STD | BN_TAIKO | BN_CTB | BN_MANIA
    PANEL_MANAGE_CLANS = MOD_MANAGE_CLANS
    PANEL_VIEW_IPS = MOD_MANAGE_USERS
    PANEL_ERROR_LOGS = DEV_VIEW_ERROR_LOGS
    PANEL_VIEW_TOP_SCORES = MOD_MANAGE_USERS
    USER_TOURNAMENT_STAFF = TOURNAMENT_STAFF
    BOT_USER = BOT
